export const productosjs = [
        {
                id: 0,
                nombre: "Corpiño con aro",
                precio: 3500,
                arrayImg: ["./img/arco.jpg"],
                img: "./img/arco.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "sujetadores",
                categoríaEspecifica: "con aro",
                detalles: "Acá van los detallesLorem ipsum dolor sit amet consectetur, adipisicing elit. Totam accusantium, ullam, doloremque officia dolores inventore dolor soluta ipsa officiis sint, aspernatur eaque? Facere perspiciatis et a veritatis! Voluptas, est odit minima quod ipsa pariatur doloribus sapiente corrupti nobis iste et quae quibusdam. Quae aliquam neque rerum natus velit optio sed aspernatur debitis nihil dolorum. Aperiam, numquam labore. Ducimus distinctio sed provident maxime nulla, atque impedit eveniet doloribus! Labore illum odit deserunt quo, delectus molestiae eius! Nisi, facere vel? Porro ullam error."
        },
        {
                id: 1,
                nombre: "Corpiño triangulo",
                precio: 3200,
                arrayImg: ["./img/triangulo.jpg"],
                img: "./img/triangulo.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "sujetadores",
                categoríaEspecifica: "triangulo",
                detalles: "Acá van los detalles"
        },
        {
                id: 2,
                nombre: "Tanga",
                precio: 2000,
                arrayImg: ["./img/tanga.jpg"],
                img: "./img/tanga.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "tanga",
                detalles: "Acá van los detalles"
        },
        {
                id: 3,
                nombre: "Vedetina",
                precio: 2200,
                arrayImg: ["./img/vedetina.jpg"],
                img: "./img/vedetina.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "vedetina",
                detalles: "Acá van los detalles"
        },
        {
                id: 4,
                nombre: "Culotte",
                precio: 2300,
                arrayImg: ["./img/culotte.jpg"],
                img: "./img/culotte.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "culotte",
                detalles: "Acá van los detalles"
        },
        {
                id: 5,
                nombre: "Portaligas",
                precio: 3500,
                arrayImg: ["./img/portaligas.jpg"],
                img: "./img/portaligas.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "accesorios",
                categoríaEspecifica: "portaliga",
                detalles: "Acá van los detalles"
        },
        {
                id: 6,
                nombre: "Corpiño con aro bajo",
                precio: 3000,
                arrayImg: ["./img/arobajo.jpg", "./img/vedetina.jpg","./img/con-aro-img2.jpeg"],
                img: "./img/arobajo.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "sujetadores",
                categoríaEspecifica: "con aro",
                detalles: "Acá van los detalles"
        },
        {
                id: 7,
                nombre: "Bombacha Abierta",
                precio: 2700,
                arrayImg: ["./img/abierta.jpg",],
                img: "./img/abierta.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "abierta",
                detalles: "Acá van los detalles"
        },
        {
                id: 8,
                nombre: "Giftcard 5000",
                precio: 5000,
                arrayImg: ["./img/giftcard.jpg"],
                img: "./img/giftcard.jpg",
                stock: 5,
                coleccion: "Muérdago",
                categoria: "giftcards",
                categoríaEspecifica: "giftcard",
                detalles: "Acá van los detalles"
        }
]
