export const productosjs = [
        {
                id: 0,
                nombre: "Corpiño con aro",
                precio: 3500,
                arrayImg: ["./img/arco.jpg"],
                img: "./img/arco.jpg",
                tallesup: [26,28,30,32,34,36,38,40,42],
                copa: ["b","c","d","dd","e","ee"],
                talleinf: [],
                ligas: [],
                arrayStock:[
                        {talle: "26b", stock: 1},{talle: "26c", stock: 2},{talle: "26d", stock: 3},{talle: "26dd", stock: 4},{talle: "26e", stock: 5},{talle: "26ee", stock: 6},
                        {talle: "28b", stock: 1},{talle: "28c", stock: 2},{talle: "28d", stock: 3},{talle: "28dd", stock: 4},{talle: "28e", stock: 5},{talle: "28ee", stock: 6},
                        {talle: "30b", stock: 1},{talle: "30c", stock: 2},{talle: "30d", stock: 3},{talle: "30dd", stock: 4},{talle: "30e", stock: 5},{talle: "30ee", stock: 6},
                        {talle: "32b", stock: 1},{talle: "32c", stock: 2},{talle: "32d", stock: 3},{talle: "32dd", stock: 4},{talle: "32e", stock: 5},{talle: "32ee", stock: 6},
                        {talle: "34b", stock: 1},{talle: "34c", stock: 2},{talle: "34d", stock: 3},{talle: "34dd", stock: 4},{talle: "34e", stock: 5},{talle: "34ee", stock: 6},
                        {talle: "36b", stock: 1},{talle: "36c", stock: 2},{talle: "36d", stock: 3},{talle: "36dd", stock: 4},{talle: "36e", stock: 5},{talle: "36ee", stock: 6},
                        {talle: "38b", stock: 1},{talle: "38c", stock: 2},{talle: "38d", stock: 3},{talle: "38dd", stock: 4},{talle: "38e", stock: 5},{talle: "38ee", stock: 6},
                        {talle: "40b", stock: 1},{talle: "40c", stock: 2},{talle: "40d", stock: 3},{talle: "40dd", stock: 4},{talle: "40e", stock: 5},{talle: "40ee", stock: 6},
                        {talle: "42b", stock: 1},{talle: "42c", stock: 2},{talle: "42d", stock: 3},{talle: "42dd", stock: 4},{talle: "42e", stock: 5},{talle: "42ee", stock: 6}
                ],
                coleccion: "Muérdago",
                categoria: "sujetadores",
                categoríaEspecifica: "con aro",
                detalles: "Acá van los detallesLorem ipsum dolor sit amet consectetur, adipisicing elit. Totam accusantium, ullam, doloremque officia dolores inventore dolor soluta ipsa officiis sint, aspernatur eaque? Facere perspiciatis et a veritatis! Voluptas, est odit minima quod ipsa pariatur doloribus sapiente corrupti nobis iste et quae quibusdam. Quae aliquam neque rerum natus velit optio sed aspernatur debitis nihil dolorum. Aperiam, numquam labore. Ducimus distinctio sed provident maxime nulla, atque impedit eveniet doloribus! Labore illum odit deserunt quo, delectus molestiae eius! Nisi, facere vel? Porro ullam error."
        },
        {
                id: 1,
                nombre: "Corpiño triangulo",
                precio: 3200,
                arrayImg: ["./img/triangulo.jpg"],
                img: "./img/triangulo.jpg",
                tallesup: [26,28,30,32,34,36,38,40,42],
                copa: ["b","c","d","dd","e","ee"],
                talleinf: [],
                ligas: [],
                arrayStock:[
                        {talle: "26b", stock: 1},{talle: "26c", stock: 2},{talle: "26d", stock: 3},{talle: "26dd", stock: 4},{talle: "26e", stock: 5},{talle: "26ee", stock: 6},
                        {talle: "28b", stock: 1},{talle: "28c", stock: 2},{talle: "28d", stock: 3},{talle: "28dd", stock: 4},{talle: "28e", stock: 5},{talle: "28ee", stock: 6},
                        {talle: "30b", stock: 1},{talle: "30c", stock: 2},{talle: "30d", stock: 3},{talle: "30dd", stock: 4},{talle: "30e", stock: 5},{talle: "30ee", stock: 6},
                        {talle: "32b", stock: 1},{talle: "32c", stock: 2},{talle: "32d", stock: 3},{talle: "32dd", stock: 4},{talle: "32e", stock: 5},{talle: "32ee", stock: 6},
                        {talle: "34b", stock: 1},{talle: "34c", stock: 2},{talle: "34d", stock: 3},{talle: "34dd", stock: 4},{talle: "34e", stock: 5},{talle: "34ee", stock: 6},
                        {talle: "36b", stock: 1},{talle: "36c", stock: 2},{talle: "36d", stock: 3},{talle: "36dd", stock: 4},{talle: "36e", stock: 5},{talle: "36ee", stock: 6},
                        {talle: "38b", stock: 1},{talle: "38c", stock: 2},{talle: "38d", stock: 3},{talle: "38dd", stock: 4},{talle: "38e", stock: 5},{talle: "38ee", stock: 6},
                        {talle: "40b", stock: 1},{talle: "40c", stock: 2},{talle: "40d", stock: 3},{talle: "40dd", stock: 4},{talle: "40e", stock: 5},{talle: "40ee", stock: 6},
                        {talle: "42b", stock: 1},{talle: "42c", stock: 2},{talle: "42d", stock: 3},{talle: "42dd", stock: 4},{talle: "42e", stock: 5},{talle: "42ee", stock: 6}
                ],
                coleccion: "Muérdago",
                categoria: "sujetadores",
                categoríaEspecifica: "triangulo",
                detalles: "Acá van los detalles"
        },
        {
                id: 2,
                nombre: "Tanga",
                precio: 2000,
                arrayImg: ["./img/tanga.jpg"],
                img: "./img/tanga.jpg",
                tallesup: [],
                copa: [],
                talleinf: ["2xs","xs","s","m","l","xl","2xl","3xl","4xl","5xl"],
                ligas: [],
                arrayStock:[
                        {talle: "2xs", stock: 1},{talle: "xs", stock: 2},{talle: "s", stock: 3},{talle:"m", stock: 4},{talle: "l", stock: 5},{talle: "xl", stock: 6},
                        {talle: "2xl", stock: 1},{talle: "3xl", stock: 2},{talle: "4xl", stock: 3},{talle:"5xl", stock: 4}
                ],
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "tanga",
                detalles: "Acá van los detalles"
        },
        {
                id: 3,
                nombre: "Vedetina",
                precio: 2200,
                arrayImg: ["./img/vedetina.jpg"],
                img: "./img/vedetina.jpg",
                tallesup: [],
                copa: [],
                talleinf: ["2xs","xs","s","m","l","xl","2xl","3xl","4xl","5xl"],
                ligas: [],
                arrayStock:[
                        {talle: "2xs", stock: 1},{talle: "xs", stock: 2},{talle: "s", stock: 3},{talle:"m", stock: 4},{talle: "l", stock: 5},{talle: "xl", stock: 6},
                        {talle: "2xl", stock: 1},{talle: "3xl", stock: 2},{talle: "4xl", stock: 3},{talle:"5xl", stock: 4}
                ],
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "vedetina",
                detalles: "Acá van los detalles"
        },
        {
                id: 4,
                nombre: "Culotte",
                precio: 2300,
                arrayImg: ["./img/culotte.jpg"],
                img: "./img/culotte.jpg",
                tallesup: [],
                copa: [],
                talleinf: ["2xs","xs","s","m","l","xl","2xl","3xl","4xl","5xl"],
                ligas: [],
                arrayStock:[
                        {talle: "2xs", stock: 1},{talle: "xs", stock: 2},{talle: "s", stock: 3},{talle:"m", stock: 4},{talle: "l", stock: 5},{talle: "xl", stock: 6},
                        {talle: "2xl", stock: 1},{talle: "3xl", stock: 2},{talle: "4xl", stock: 3},{talle:"5xl", stock: 4}
                ],
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "culotte",
                detalles: "Acá van los detalles"
        },
        {
                id: 5,
                nombre: "Portaligas",
                precio: 3500,
                arrayImg: ["./img/portaligas.jpg"],
                img: "./img/portaligas.jpg",
                tallesup: [],
                copa: [],
                talleinf: ["2xs","xs","s","m","l","xl","2xl","3xl","4xl","5xl"],
                ligas: [1,2,3,4],
                arrayStock:[
                        {talle: "2xs1", stock: 1},{talle: "2xs2", stock: 2},{talle: "2xs3", stock: 3},{talle:"2xs4", stock: 4},
                        {talle: "xs1", stock: 1},{talle: "xs2", stock: 2},{talle: "xs3", stock: 3},{talle:"xs4", stock: 4},
                        {talle: "s1", stock: 1},{talle: "s2", stock: 2},{talle: "s3", stock: 3},{talle:"s4", stock: 4},
                        {talle: "m1", stock: 1},{talle: "m2", stock: 2},{talle: "m3", stock: 3},{talle:"m4", stock: 4},
                        {talle: "l1", stock: 1},{talle: "l2", stock: 2},{talle: "l3", stock: 3},{talle:"l4", stock: 4},
                        {talle: "xl1", stock: 1},{talle: "xl2", stock: 2},{talle: "xls3", stock: 3},{talle:"xls4", stock: 4},
                        {talle: "2xl1", stock: 1},{talle: "2xl2", stock: 2},{talle: "2xl3", stock: 3},{talle:"2xl4", stock: 4},
                        {talle: "3xl1", stock: 1},{talle: "3xl2", stock: 2},{talle: "3xl3", stock: 3},{talle:"3xl4", stock: 4},
                        {talle: "4xl1", stock: 1},{talle: "4xl2", stock: 2},{talle: "4xl3", stock: 3},{talle:"4xl4", stock: 4},
                        {talle: "5xl1", stock: 1},{talle: "5xl2", stock: 2},{talle: "5xl3", stock: 3},{talle:"5xl4", stock: 4}
                ],
                coleccion: "Muérdago",
                categoria: "accesorios",
                categoríaEspecifica: "portaliga",
                detalles: "Acá van los detalles"
        },
        {
                id: 6,
                nombre: "Corpiño con aro bajo",
                precio: 3000,
                arrayImg: ["./img/arobajo.jpg", "./img/vedetina.jpg","./img/con-aro-img2.jpeg"],
                img: "./img/arobajo.jpg",
                tallesup: [26,28,30,32,34,36,38,40,42],
                copa: ["b","c","d","dd","e","ee"],
                talleinf: [],
                ligas: [],
                arrayStock:[
                        {talle: "26b", stock: 1},{talle: "26c", stock: 2},{talle: "26d", stock: 3},{talle: "26dd", stock: 4},{talle: "26e", stock: 5},{talle: "26ee", stock: 6},
                        {talle: "28b", stock: 1},{talle: "28c", stock: 2},{talle: "28d", stock: 3},{talle: "28dd", stock: 4},{talle: "28e", stock: 5},{talle: "28ee", stock: 6},
                        {talle: "30b", stock: 1},{talle: "30c", stock: 2},{talle: "30d", stock: 3},{talle: "30dd", stock: 4},{talle: "30e", stock: 5},{talle: "30ee", stock: 6},
                        {talle: "32b", stock: 1},{talle: "32c", stock: 2},{talle: "32d", stock: 3},{talle: "32dd", stock: 4},{talle: "32e", stock: 5},{talle: "32ee", stock: 6},
                        {talle: "34b", stock: 1},{talle: "34c", stock: 2},{talle: "34d", stock: 3},{talle: "34dd", stock: 4},{talle: "34e", stock: 5},{talle: "34ee", stock: 6},
                        {talle: "36b", stock: 1},{talle: "36c", stock: 2},{talle: "36d", stock: 3},{talle: "36dd", stock: 4},{talle: "36e", stock: 5},{talle: "36ee", stock: 6},
                        {talle: "38b", stock: 1},{talle: "38c", stock: 2},{talle: "38d", stock: 3},{talle: "38dd", stock: 4},{talle: "38e", stock: 5},{talle: "38ee", stock: 6},
                        {talle: "40b", stock: 1},{talle: "40c", stock: 2},{talle: "40d", stock: 3},{talle: "40dd", stock: 4},{talle: "40e", stock: 5},{talle: "40ee", stock: 6},
                        {talle: "42b", stock: 1},{talle: "42c", stock: 2},{talle: "42d", stock: 3},{talle: "42dd", stock: 4},{talle: "42e", stock: 5},{talle: "42ee", stock: 6}
                ],
                stock: 5,
                coleccion: "Muérdago",
                categoria: "sujetadores",
                categoríaEspecifica: "con aro",
                detalles: "Acá van los detalles"
        },
        {
                id: 7,
                nombre: "Abierta",
                precio: 2700,
                arrayImg: ["./img/abierta.jpg",],
                img: "./img/abierta.jpg",
                tallesup: [],
                copa: [],
                talleinf: ["2xs","xs","s","m","l","xl","2xl","3xl","4xl","5xl"],
                ligas: [],
                arrayStock:[
                        {talle: "2xs", stock: 1},{talle: "xs", stock: 2},{talle: "s", stock: 3},{talle:"m", stock: 4},{talle: "l", stock: 5},{talle: "xl", stock: 6},
                        {talle: "2xl", stock: 1},{talle: "3xl", stock: 2},{talle: "4xl", stock: 3},{talle:"28dd", stock: 4},{talle: "28e", stock: 5},{talle: "28ee", stock: 6},
                        {talle: "5xl"}
                ],
                coleccion: "Muérdago",
                categoria: "bombachas",
                categoríaEspecifica: "abierta",
                detalles: "Acá van los detalles"
        },
        {
                id: 8,
                nombre: "Giftcard 5000",
                precio: 5000,
                arrayImg: ["./img/giftcard.jpg"],
                img: "./img/giftcard.jpg",
                tallesup: [],
                copa: [],
                talleinf: [],
                ligas: [],
                arrayStock:[
                        {talle: "2xs", stock: 1},{talle: "xs", stock: 2},{talle: "s", stock: 3},{talle:"m", stock: 4},{talle: "l", stock: 5},{talle: "xl", stock: 6},
                        {talle: "2xl", stock: 1},{talle: "3xl", stock: 2},{talle: "4xl", stock: 3},{talle:"28dd", stock: 4},{talle: "28e", stock: 5},{talle: "28ee", stock: 6},
                        {talle: "5xl"}
                ],
                coleccion: "Muérdago",
                categoria: "giftcards",
                categoríaEspecifica: "giftcard",
                detalles: "Acá van los detalles"
        }
]
